ALTER TABLE "Purchase" ADD COLUMN IF NOT EXISTS "offerId" TEXT;
CREATE INDEX IF NOT EXISTS "Purchase_offerId_idx" ON "Purchase"("offerId");

ALTER TABLE "Offer" ADD COLUMN IF NOT EXISTS "audience" TEXT NOT NULL DEFAULT 'ALL';
ALTER TABLE "Offer" ADD COLUMN IF NOT EXISTS "targetUserId" TEXT;
ALTER TABLE "Offer" ADD COLUMN IF NOT EXISTS "targetVip" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Offer" ADD COLUMN IF NOT EXISTS "minTasks" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Offer" ADD COLUMN IF NOT EXISTS "maxTasks" INTEGER;
ALTER TABLE "Offer" ADD COLUMN IF NOT EXISTS "minPoints" BIGINT NOT NULL DEFAULT 0;
ALTER TABLE "Offer" ADD COLUMN IF NOT EXISTS "maxPoints" BIGINT;
ALTER TABLE "Offer" ADD COLUMN IF NOT EXISTS "pointsOverride" BIGINT;
ALTER TABLE "Offer" ADD COLUMN IF NOT EXISTS "showNotification" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Offer" ADD COLUMN IF NOT EXISTS "notificationSent" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Offer" ADD COLUMN IF NOT EXISTS "maxClaimsPerUser" INTEGER;
CREATE INDEX IF NOT EXISTS "Offer_audience_targetUserId_idx" ON "Offer"("audience", "targetUserId");

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Purchase_offerId_fkey') THEN
    ALTER TABLE "Purchase" ADD CONSTRAINT "Purchase_offerId_fkey" FOREIGN KEY ("offerId") REFERENCES "Offer"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;
